formatter: markdown

content: |-
  ## Usage
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: replace
  content: |-
    ## Usage

    ```hcl
    {{ include "examples/basic/main.tf" }}
    ```
  template: |-
    # terraform-aws-mwaa

    Terraform module to provision Amazon Managed Workflows for Apache Airflow (MWAA)

    __NOTE:__ This module is a hard fork of [CloudPosse's terraform module](https://github.com/cloudposse/terraform-aws-mwaa)

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
